#!/bin/bash

PACKAGENAME=$1
DEPENDENCY=$2
WHERE=$3

if [ ! -f /opt/awx-rpm-v2/versions/deps/python-$PACKAGENAME.spec ]; then
	if [ ! -f /opt/awx-rpm-v2/versions/deps/python3-$PACKAGENAME.spec ]; then
		echo "Package $PACKAGENAME doesn't exist"
		exit 0
	else
		FILENAME=python3-$PACKAGENAME
	fi
else
	FILENAME=python-$PACKAGENAME
fi

if [ -z "${DEPENDENCY}" ]; then
	echo "Please specify dependency to add"
	exit 2
fi

if [[ "${WHERE}" != both ]] && [[ "${WHERE}" != build ]] && [[ "${WHERE}" != runtime ]] ; then
        echo "Please specify where to add the dependency"
	echo "Either 'build', 'run' or 'both'"
fi	

if [[ "${WHERE}" == both ]] || [[ "${WHERE}" == build ]]; then
	sed -i "0,/BuildRequires/s//BuildRequires: $(echo $DEPENDENCY)\n&/" /opt/awx-rpm-v2/versions/deps/$FILENAME.spec
fi

if [[ "${WHERE}" == both ]] || [[ "${WHERE}" == runtime ]]; then
        sed -i "0,/BuildRequires/s//Requires: $(echo $DEPENDENCY)\n&/" /opt/awx-rpm-v2/versions/deps/$FILENAME.spec
fi

/opt/awx-rpm-v2/new-scripts/buildsrc $FILENAME
