#!/bin/bash
source $(dirname "$0")/common-functions

VERSION=$(get_version)

PACKAGE=$1

if [ ! -d "/opt/awx-rpm-v2/versions/deps" ]; then
        echo "SPECs for version $VERSION not generated"
        exit 1
fi

if [ -d "/opt/awx-rpm-v2/rpmbuilds/$VERSION/SRPMS" ] && [ "$PACKAGE" == "" ]; then
	if [ "$PACKAGE" != "force" ]; then
		echo "SRPMs already generated, apply force to regenerate"
		exit
	else
		rm -rf "/opt/awx-rpm-v2/rpmbuilds/$VERSION/SRPMS"
	fi 
fi

cd "/opt/awx-rpm-v2/versions/deps/"

if [[ ${PACKAGE} != "" ]];then
	echo "Building SRPM for $PACKAGE for version $VERSION"
	if [ -f $PACKAGE.spec ];then
                rpmbuild -bs --define "_topdir /opt/awx-rpm-v2/rpmbuilds/$VERSION/" $PACKAGE.spec
        else
		rpmbuild -bs --define "_topdir /opt/awx-rpm-v2/rpmbuilds/$VERSION/" python-$PACKAGE.spec
	fi
	exit 0
fi

for i in `ls *.spec`;do 
	echo "Building SRPMS for version $VERSION"
	rpmbuild -bs --define "_topdir /opt/awx-rpm-v2/rpmbuilds/$VERSION/" $i 
done
