#!/bin/bash

source $(dirname "$0")/common-functions

OLDVERSION=$(get_version)

echo "Currently on version $OLDVERSION"

if [ -z "$1" ]; then
        echo "Please provide AWX version"
        exit 1
fi

VERSION=$1

cd /opt/awx-rpm-v2/versions/

git commit -qam "Changes to Branch $VERSION"

if [[ `git branch |grep $VERSION | wc -l` -gt 0 ]]; then
	git checkout $VERSION
	VERSIONEXISTS=1
else
	echo "Version $VERSION hasn't been generated yet"
	VERSIONEXISTS=0
fi

cd /opt/awx-rpm-v2/awx/

git checkout -q devel
git pull -q

if [ `git tag |grep $VERSION` ]; then
        git -c advice.detachedHead=false checkout $VERSION
	echo "Version changed to: $VERSION"
	if [[ $VERSIONEXISTS == 0 ]];then
		echo "Creating New Version"
		cd /opt/awx-rpm-v2/versions/
		git switch --orphan $VERSION
		touch /opt/awx-rpm-v2/versions/VERSION-$VERSION
		git add /opt/awx-rpm-v2/versions/VERSION-$VERSION
		git commit -am "Created version: $VERSION"
	fi
else
        echo "Version $VERSION doesn't exist"
	VERSION=$OLDVERSION
	cd /opt/awx-rpm-v2/versions/
	git checkout -q $VERSION
fi

cd /opt/awx-rpm-v2/versions/
git push origin -q --all

echo "$VERSION" > /opt/awx-rpm-v2/working-version

