#!/bin/bash

source $(dirname "$0")/common-functions

VERSION=$(get_version)

if [ ! -d "/opt/awx-rpm-v2/versions/deps" ]; then
        echo "SPECs for version $VERSION not generated"
        exit 1
fi

FORMAT=$2

cd "/opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

BUILT=0
MISSING=0

if [[ "$FORMAT" == "md" ]]; then
	echo "# Package build status for version: $VERSION"
else
	echo "Package build status for version: $VERSION"
fi

for i in `ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/SRPMS/`;do 
	PACKAGE=$(echo $i |sed 's/.src.rpm//g' |sed 's/python/python3/g' | sed 's/python33/python3/g')
	PACKAGEPRESENT=$(ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/$PACKAGE* 2> /dev/null)
	PYTHONPACKAGE=$(echo $PACKAGE | sed 's/python3/python3-python/g')
	PYTHONPACKAGEPRESENT=$(ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/$PYTHONPACKAGE* 2> /dev/null)
	PYTHON3PACKAGE=$(echo $PACKAGE | sed 's/python3/python3-python3/g')
        PYTHON3PACKAGEPRESENT=$(ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/$PYTHON3PACKAGE* 2> /dev/null)
	ALTPACKAGE=$(echo $PACKAGE | sed 's/python3/python/g')
	ALTPACKAGEPRESENT=$(ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/$ALTPACKAGE* 2> /dev/null)
	GITPYTHON=$(echo $PACKAGE | sed 's/gitpython3/gitpython/g')
	GITPYTHONPACKAGEPRESENT=$(ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/$GITPYTHON* 2> /dev/null)
        if [[ "$PACKAGEPRESENT" != "" ]] || [[ "$PYTHONPACKAGEPRESENT" != "" ]] || [[ "$PYTHON3PACKAGEPRESENT" != "" ]] || [[ "$ALTPACKAGEPRESENT" != "" ]] || [[ "$GITPYTHONPACKAGEPRESENT" != "" ]]; then
		BUILT=$((BUILT+1)) 
		if [[ "$1" == "all" ]]; then
			if [[ "$FORMAT" == "md" ]]; then
				echo "* $PACKAGE - $i - Built"
			else 
				echo -e "$PACKAGE - $i - ${GREEN}Built${NC}"
			fi
		fi 
	else  
		if [[ "$FORMAT" == "md" ]]; then
			echo "* $PACKAGE - $i - Missing"
		else
			echo -e "$PACKAGE - $i - ${RED}Missing${NC}"
		fi
		MISSING=$((MISSING+1))
	fi 
done

TOTAL=$(($MISSING+$BUILT))

echo
echo "$TOTAL total packages, $BUILT packages built successfully, $MISSING packages left to fix"

