#!/usr/bin/env python3

import argparse
import os
import subprocess
import urllib.request
import configparser

parser = argparse.ArgumentParser(description='AWX-RPM management')
parser.add_argument(metavar='VERSION',help="Select version",dest='version')

args = parser.parse_args()
version = args.version

print("Using version: "+version)
print("Settings excludelists")
url = "https://rpm.awx.wiki/AWX-RPM/excludelists/awx-rpm-"+version+".el9"
response = urllib.request.urlopen(url)
data = response.read()
excludepackages = data.decode('utf-8')
excludeline = ""
for each_line in excludepackages:
        package = each_line.replace("\n", ",").strip()
        excludeline = excludeline + package

print("Setting excludelist for EPEL")
repo = configparser.ConfigParser()
repo.read('/etc/yum.repos.d/epel.repo')
repo['epel']['exclude'] = excludeline
with open('/etc/yum.repos.d/epel.repo', 'w') as repofile:
        repo.write(repofile)

print("Setting excludelist for PyPI")
repo = configparser.ConfigParser()
repo.read('/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_copr:PyPI.repo')
repo['copr:copr.fedorainfracloud.org:group_copr:PyPI']['exclude'] = excludeline
with open('/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_copr:PyPI.repo', 'w') as repofile:
        repo.write(repofile)

