#!/bin/bash

source $(dirname "$0")/common-functions

VERSION=$(get_version)

if [ -d "/opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS" ]; then
        if [ "$1" == "force" ]; then
                echo "Removing built packages"
		rm -rf "/opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS"
        fi
fi

echo "Creating output folder"
mkdir -p "/opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/"

#cd "/opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/"

mock -r epel-9-x86_64 --clean

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

for i in `ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/SRPMS/`;do
        PACKAGE=$(echo $i |sed 's/.src.rpm//g' |sed 's/python/python3/g' | sed 's/python33/python3/g')
        PACKAGEPRESENT=$(ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/$PACKAGE* 2> /dev/null)
        PYTHONPACKAGE=$(echo $PACKAGE | sed 's/python3/python3-python/g')
        PYTHONPACKAGEPRESENT=$(ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/$PYTHONPACKAGE* 2> /dev/null)
        PYTHON3PACKAGE=$(echo $PACKAGE | sed 's/python3/python3-python3/g')
        PYTHON3PACKAGEPRESENT=$(ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/$PYTHON3PACKAGE* 2> /dev/null)
        ALTPACKAGE=$(echo $PACKAGE | sed 's/python3/python/g')
        ALTPACKAGEPRESENT=$(ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/$ALTPACKAGE* 2> /dev/null)

	if [[ "$PACKAGEPRESENT" != "" ]] || [[ "$PYTHONPACKAGEPRESENT" != "" ]] || [[ "$PYTHON3PACKAGEPRESENT" != "" ]] || [[ "$ALTPACKAGEPRESENT" != "" ]]; then        
		echo -e "$PACKAGE ${GREEN}Built${NC}"
	else
	        echo -e "$PACKAGE ${RED}Missing${NC}... Building.."
        	build_rpm $i
	fi
done

