#!/bin/bash

source $(dirname "$0")/common-functions

VERSION=$(get_version)

echo "Generating SPECs for version $VERSION"

PACKAGE=$1
PACKAGEVERSION=$2

cd /opt/awx-rpm-v2/awx/

git checkout -q devel
git pull -q

if [ `git tag |grep $VERSION` ]; then
	git -c advice.detachedHead=false checkout -q $VERSION
else
	echo "Version $VERSION doesn't exist"
	exit 1
fi

if [ -d "/opt/awx-rpm-v2/versions/deps" ]; then
	if [[ $PACKAGE == "force" ]] ; then
		echo "Removing packages"
		rm -rf "/opt/awx-rpm-v2/versions/deps"
		exit 0
	elif [[ $PACKAGE == "" ]]; then
		echo "Version is already created, force to overwrite"
		exit 1
	else
		echo "Adding package $PACKAGE $VERSION"
	fi
fi

mkdir -p /opt/awx-rpm-v2/versions/deps

cat /opt/awx-rpm-v2/awx/requirements/requirements.txt | grep -v "#" > /opt/awx-rpm-v2/versions/deps/requirements.txt

cd /opt/awx-rpm-v2/versions/deps/

if [[ $PACKAGE == "" ]];then
	for i in `cat /opt/awx-rpm-v2/versions/deps/requirements.txt | sed 's/\[.*\]//'`;do 
		PACKAGE=$(echo $i | cut -f1 -d"=") 
		PACKAGEVERSION=$(echo $i | cut -f3 -d"=")
		echo "Generating SPEC-file for $PACKAGE version $PACKAGEVERSION"
		pyp2spec --license gpl -v $PACKAGEVERSION $PACKAGE 
	done
else
        if [[ $PACKAGEVERSION == "" ]];then
		echo "Generating SPEC-file for $PACKAGE"
        	pyp2spec --license gpl $PACKAGE
	else
		echo "Generating SPEC-file for $PACKAGE version $PACKAGEVERSION"
	        pyp2spec --license gpl -v $PACKAGEVERSION $PACKAGE
	fi
fi

mkdir -p /opt/awx-rpm-v2/versions/deps/original

cp /opt/awx-rpm-v2/versions/deps/python-$PACKAGE.spec /opt/awx-rpm-v2/versions/deps/python-$PACKAGE.conf /opt/awx-rpm-v2/versions/deps/original/

