#!/bin/bash

PACKAGENAME=$1

if [ ! -f /opt/awx-rpm-v2/versions/deps/python-$PACKAGENAME.spec ]; then
	if [ ! -f /opt/awx-rpm-v2/versions/deps/python3-$PACKAGENAME.spec ]; then
		echo "Package $PACKAGENAME doesn't exist"
		exit 0
	else
		FILENAME=python3-$PACKAGENAME
	fi
else
	FILENAME=python-$PACKAGENAME
fi

sed -i "/^%pyproject_extras_subpkg/d" /opt/awx-rpm-v2/versions/deps/$FILENAME.spec
sed -i "s/^%pyproject_buildrequires.*/%pyproject_buildrequires/g" /opt/awx-rpm-v2/versions/deps/$FILENAME.spec

/opt/awx-rpm-v2/new-scripts/buildsrc $FILENAME
