#!/bin/bash

source $(dirname "$0")/common-functions

VERSION=$(get_version)

PACKAGE=$1
if [[ "$2" == "nobuild" ]]; then
	PACKAGEVERSION=""
else
	PACKAGEVERSION=$2
fi

if [[ "$3" == "nobuild" ]] || [[ "$2" == "nobuild" ]]; then
	BUILDSRC=0
else
	BUILDSRC=1
fi

if [[ $PACKAGE == "" ]] ;then
	echo "Please define buildversion and packagename"
	exit 0
fi

$(dirname "$0")/pypi2spec $PACKAGE $PACKAGEVERSION
$(dirname "$0")/getsources $PACKAGE $PACKAGEVERSION
if [[ "$BUILDSRC" == "1" ]];then
	$(dirname "$0")/buildsrc $PACKAGE $PACKAGEVERSION
fi

if [[ $PACKAGEVERSION == "" ]];then
	echo "$PACKAGE" >> /opt/awx-rpm-v2/versions/deps/extra-deps.txt
else
	echo "$PACKAGE==$PACKAGEVERSION" >> /opt/awx-rpm-v2/versions/deps/extra-deps.txt
fi
