#!/bin/bash

OLDVERSION=$(cat /opt/awx-rpm-v2/working-version)

if [ -z "$1" ]; then
        echo "Please provide AWX version"
        exit 1
fi

VERSION=$1

cd /opt/awx-rpm-v2/versions/

if [ `git tag |grep $VERSION` ]; then
	git checkout $VERSION
else
	echo "Version $VERSION hasn't been generated yet"
	exit 0
fi

cd /opt/awx-rpm-v2/awx/

git checkout -q devel
git pull -q

if [ `git tag |grep $VERSION` ]; then
        git -c advice.detachedHead=false checkout -q $VERSION
	echo "Version changed to: $VERSION"
else
        echo "Version $VERSION doesn't exist"
	/opt/awx-rpm-v2/scripts/changeversion $OLDVERSION
	VERSION=$OLDVERSION
fi

echo "$VERSION" > /opt/awx-rpm-v2/working-version

