#!/bin/bash

VERSION=$(cat /opt/awx-rpm-v2/working-version)

if [ ! -z $1 ] && [ "$1" != "force" ] && [ "$1" != "all" ];then
        VERSION=$1
fi

if [ ! -d "/opt/awx-rpm-v2/deps/$VERSION" ]; then
        echo "SPECs for version $VERSION not generated"
        exit 1
fi

if [ -d "/opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS" ]; then
        if [ "$2" == "force" ] || [ "$1" == "force" ]; then
                rm -rf "/opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS"
        fi
fi

cd "/opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

BUILT=0
MISSING=0

for i in `ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/SRPMS/`;do 
	PACKAGE=$(echo $i |sed 's/.src.rpm//g' |sed 's/python/python3/g' | sed 's/python33/python3/g')
	PACKAGEPRESENT=$(ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/$PACKAGE* 2> /dev/null)
	PYTHONPACKAGE=$(echo $PACKAGE | sed 's/python3/python3-python/g')
	PYTHONPACKAGEPRESENT=$(ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/$PYTHONPACKAGE* 2> /dev/null)
	PYTHON3PACKAGE=$(echo $PACKAGE | sed 's/python3/python3-python3/g')
        PYTHON3PACKAGEPRESENT=$(ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/$PYTHON3PACKAGE* 2> /dev/null)
	ALTPACKAGE=$(echo $PACKAGE | sed 's/python3/python/g')
	ALTPACKAGEPRESENT=$(ls /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/$ALTPACKAGE* 2> /dev/null)
        if [[ "$PACKAGEPRESENT" != "" ]] || [[ "$PYTHONPACKAGEPRESENT" != "" ]] || [[ "$PYTHON3PACKAGEPRESENT" != "" ]] || [[ "$ALTPACKAGEPRESENT" != "" ]]; then
		BUILT=$((BUILT+1)) 
		if [[ "$1" == "all" ]]; then 
			echo -e "$PACKAGE ${GREEN}Built${NC}"
		fi 
	else  
		echo -e "$PACKAGE ${RED}Missing${NC}"
		MISSING=$((MISSING+1))
	fi 
done

TOTAL=$(($MISSING+$BUILT))

echo
echo "$TOTAL total packages, $BUILT packages built successfully, $MISSING packages left to fix"

