#!/bin/bash

OLDVERSION=$1
NEWVERSION=$2

if [[ $OLDVERSION == "" ]] ;then
        echo "Please define old buildversion"
        exit 0
fi

if [[ $NEWVERSION == "" ]] ;then
        echo "Please define new buildversion"
        exit 0
fi


