#!/bin/bash

VERSION=$(cat /opt/awx-rpm-v2/working-version)

cd /opt/awx-rpm-v2/

cp /opt/awx-rpm-v2/awx-rpm/patch-$VERSION.patch /opt/awx-rpm-v2/rpmbuilds/$VERSION/SOURCES/

#tar zcf /opt/awx-rpm-v2/rpmbuilds/$VERSION/SOURCES/awx-$VERSION.tar.gz awx/

cd /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS/

for i in `ls python* |grep -v debuginfo |grep -v debugsource | grep -v poetry`; do
	
	PACKAGENAME=$(echo $i | rev | cut -f3- -d- | rev | cut -f1- -d-)
	PACKAGEVERSION=$(echo $i | rev | cut -f2 -d- | rev)
	DEPS=$DEPS$(echo "Requires: $PACKAGENAME = $PACKAGEVERSION\r")
	BUILDDEPS=$BUILDDEPS$(echo "BuildRequires: $PACKAGENAME = $PACKAGEVERSION\r")

done

cp /opt/awx-rpm-v2/awx-rpm/awx-rpm-temp.spec /opt/awx-rpm-v2/deps/$VERSION/awx-rpm.spec

sed -i "s|¤BUILDREQUIRES¤|$BUILDDEPS|g" /opt/awx-rpm-v2/deps/$VERSION/awx-rpm.spec
sed -i "s|¤REQUIRES¤|$DEPS|g" /opt/awx-rpm-v2/deps/$VERSION/awx-rpm.spec
sed -i "s|¤VERSION¤|$VERSION|g" /opt/awx-rpm-v2/deps/$VERSION/awx-rpm.spec
sed -i "s|\r|\n|g" /opt/awx-rpm-v2/deps/$VERSION/awx-rpm.spec

rpmbuild -bs --define "_topdir /opt/awx-rpm-v2/rpmbuilds/$VERSION/" /opt/awx-rpm-v2/deps/$VERSION/awx-rpm.spec

