#!/bin/bash

source $(dirname "$0")/common-functions

VERSION=$(get_version)
PYTHONBUILD=$(get_python)

DATE=$(date +"%a %b %d %Y %r %Z %z")

PACKAGEVERSION=$1

echo "Generating source and build for receptor version: $PACKAGEVERSION for version: $VERSION"

wget -O $BASEPATH_DIR/rpmbuilds/$VERSION/SOURCES/receptor-$PACKAGEVERSION.tar.gz https://github.com/ansible/receptor/archive/refs/tags/v$PACKAGEVERSION.tar.gz

cp $BASEPATH_DIR/templates/receptor-temp.spec $BASEPATH_DIR/versions/deps/awx-rpm-receptor.spec
sed -i "s|¤VERSION¤|$PACKAGEVERSION|g" $BASEPATH_DIR/versions/deps/awx-rpm-receptor.spec
sed -i "s/%setup/%setup -n receptor-%{version}/g" $BASEPATH_DIR/versions/deps/awx-rpm-receptor.spec
sed -i "s|¤DATE¤|$DATE|g" $BASEPATH_DIR/versions/deps/awx-rpm-receptor.spec
sed -i "s|¤PYTHON3PKGVERSION¤|$PYTHONBUILD|g" $BASEPATH_DIR/versions/deps/awx-rpm-receptor.spec

rpmbuild -bs --define "_topdir $BASEPATH_DIR/rpmbuilds/$VERSION/" $BASEPATH_DIR/versions/deps/awx-rpm-receptor.spec

mock -r epel-9-x86_64 --enable-network --addrepo $BASEPATH_DIR/rpmbuilds/$VERSION/RPMS --resultdir $BASEPATH_DIR/rpmbuilds/$VERSION/RPMS-TMP/ --no-clean $BASEPATH_DIR/rpmbuilds/$VERSION/SRPMS/awx-receptor-$PACKAGEVERSION-1.el9.src.rpm --rpmbuild-opts="--nocheck" --no-cleanup-after
rm -f $BASEPATH_DIR/rpmbuilds/$VERSION/RPMS-TMP/*.src.rpm
cp $BASEPATH_DIR/rpmbuilds/$VERSION/RPMS-TMP/*.rpm $BASEPATH_DIR/rpmbuilds/$VERSION/RPMS/
createrepo_c $BASEPATH_DIR/rpmbuilds/$VERSION/RPMS/
rm -f $BASEPATH_DIR/rpmbuilds/$VERSION/RPMS-TMP/*
mock -r epel-9-x86_64 --clean

