#!/bin/bash

VERSION=$(cat /opt/awx-rpm-v2/working-version)

if [ ! -z $1 ];then
	VERSION=$1
fi

if [ ! -d "/opt/awx-rpm-v2/deps/$VERSION" ]; then
	echo "SPECs for version $VERSION not generated"
	exit 1
fi

echo "Fetching sources for version $VERSION"

cd "/opt/awx-rpm-v2/deps/$VERSION"

for i in `ls *.spec`;do 
	spectool -gR --define "_topdir /opt/awx-rpm-v2/rpmbuilds/$VERSION/" $i 
done
