#!/bin/bash

if [[ "$1" != "force" ]]; then
        NEWVERSION=$2
        FROMVERSION=$1
else
	NEWVERSION=$3
	FROMVERSION=$2
fi

cd $BASEPATH_DIR/versions/

if [ -z "$FROMVERSION" ]; then
	echo "Existing version not defined"
	echo "Select from:"
	echo
	cd $BASEPATH_DIR/versions/
        git branch -rv |cut -f2- -d\/
        exit 1
fi

if [[ `git branch -rv |cut -f2- -d\/ |grep $FROMVERSION | wc -l` -gt 0 ]]; then
        git checkout $FROMVERSION
else
        echo "Source version $FROMVERSION doesn't exists"
        exit 1
fi

if [ -z "$NEWVERSION" ]; then
        echo "Please provide New AWX version"
        echo "Select from"
	echo
        cd $BASEPATH_DIR/awx/
        git ls-remote --tags origin | cut -f3- -d\/ |grep -v "{}" |sort -Vr
	#git branch -rv |cut -f2- -d\/
        exit 1
fi

if [[ "`cd $BASEPATH_DIR/awx/ && git ls-remote --tags origin | cut -f3- -d\/ |grep -v "{}" | grep -x $NEWVERSION |wc -l`" != "1" ]]; then
	echo "Version: $NEWVERSION doesn't exist"
	exit 1
fi

rm -rf $BASEPATH_DIR/migration
mkdir -p $BASEPATH_DIR/migration/{source,orig,conf,patch,awx-rpm}
cp -ar $BASEPATH_DIR/versions/deps/extra-sources $BASEPATH_DIR/migration
mkdir -p $BASEPATH_DIR/rpmbuilds/$NEWVERSION/SOURCES/
cp $BASEPATH_DIR/versions/deps/extra-sources/* $BASEPATH_DIR/rpmbuilds/$NEWVERSION/SOURCES/
cp $BASEPATH_DIR/versions/PYTHON $BASEPATH_DIR/migration/
if [ -d $BASEPATH_DIR/versions/awx-rpm ]; then
	for i in `ls $BASEPATH_DIR/versions/awx-rpm/*-$FROMVERSION | xargs -n 1 basename`;do
		FILENAME=$(echo $i | sed "s/-$FROMVERSION/-$NEWVERSION/g")
		cp $BASEPATH_DIR/versions/awx-rpm/$i $BASEPATH_DIR/migration/awx-rpm/$FILENAME
	done
fi

cp -a $BASEPATH_DIR/versions/deps/*.spec $BASEPATH_DIR/migration/source/
rm -f $BASEPATH_DIR/migration/source/awx*
for i in `ls $BASEPATH_DIR/migration/source/`;do
	if [ -f $BASEPATH_DIR/versions/deps/original/$i ];then
		cp $BASEPATH_DIR/versions/deps/original/$i $BASEPATH_DIR/migration/orig/
	else
		cp $BASEPATH_DIR/migration/source/$i $BASEPATH_DIR/migration/orig/
	fi
done
cp -a $BASEPATH_DIR/versions/deps/*.conf $BASEPATH_DIR/migration/conf/

cd $BASEPATH_DIR/migration/

for i in `ls $BASEPATH_DIR/migration/source/`;do

	NAME=$(echo $i |cut -f1 -d.)
	diff --ignore-all-space -uNr orig/$i source/$i > $BASEPATH_DIR/migration/patch/$NAME.patch

done

find $BASEPATH_DIR/migration/patch/ -type f -empty -delete

cp $BASEPATH_DIR/versions/deps/{extra-deps.txt,remove-deps.txt,rhel-deps.txt} $BASEPATH_DIR/migration/

cd $BASEPATH_DIR/versions/

git switch --orphan $NEWVERSION

touch $BASEPATH_DIR/versions/VERSION-$NEWVERSION

git add $BASEPATH_DIR/versions/VERSION-$NEWVERSION

git commit -qam "Created Version $NEWVERSION"

git push -u origin $NEWVERSION

$BASEPATH_DIR/scripts/changeversion $NEWVERSION

$BASEPATH_DIR/scripts/pypi2spec
for i in `cat $BASEPATH_DIR/migration/extra-deps.txt`; do

	PACKAGENAME=$(echo $i | cut -f1 -d=)
	VERSION=$(echo $i | cut -f3 -d=)
	
	echo "Adding package $PACKAGENAME $VERSION"
	if [[ "$PACKAGENAME" == "$VERSION" ]];then
		$BASEPATH_DIR/scripts/addpackage $PACKAGENAME nobuild
	else 
		$BASEPATH_DIR/scripts/addpackage $PACKAGENAME $VERSION nobuild
	fi

done

cp $BASEPATH_DIR/migration/remove-deps.txt $BASEPATH_DIR/versions/deps/remove-deps.txt
cp $BASEPATH_DIR/migration/rhel-deps.txt $BASEPATH_DIR/versions/deps/rhel-deps.txt
cp -ar $BASEPATH_DIR/migration/extra-sources $BASEPATH_DIR/versions/deps/
cp $BASEPATH_DIR/migration/PYTHON $BASEPATH_DIR/versions/PYTHON
mkdir -p $BASEPATH_DIR/versions/awx-rpm
cp $BASEPATH_DIR/migration/awx-rpm/* $BASEPATH_DIR/versions/awx-rpm/

for i in `cat $BASEPATH_DIR/migration/remove-deps.txt $BASEPATH_DIR/migration/rhel-deps.txt`; do
	PACKAGENAME=$(echo $i | sed "s/python//g" | sed "s/python3//g")
	echo "Removing package $PACKAGENAME"
	rm -f $BASEPATH_DIR/versions/deps/*$PACKAGENAME.spec
	rm -f $BASEPATH_DIR/versions/deps/*$PACKAGENAME.conf
	rm -f $BASEPATH_DIR/versions/deps/original/*$PACKAGENAME.spec
        rm -f $BASEPATH_DIR/versions/deps/original/*$PACKAGENAME.conf
done

cd $BASEPATH_DIR/versions/
git add $BASEPATH_DIR/versions/*
git commit -qam "Imported from version $FROMVERSION to version $NEWVERSION"
git push

$BASEPATH_DIR/scripts/getsources

echo "Applying patches from version: $FROMVERSION"

$BASEPATH_DIR/scripts/applypatches

