#!/bin/bash

PACKAGENAME=$1
source $(dirname "$0")/common-functions

PYTHONBUILD=$(get_python)
VERSION=$(get_version)

if [ ! -f $BASEPATH_DIR/versions/deps/python-$PACKAGENAME.spec ]; then
	if [ ! -f $BASEPATH_DIR/versions/deps/python3-$PACKAGENAME.spec ]; then
		echo "Package $PACKAGENAME doesn't exist"
		exit 0
	else
		FILENAME=python3-$PACKAGENAME
	fi
else
	FILENAME=python-$PACKAGENAME
fi



sed -i '1i%global debug_package %{nil}' $BASEPATH_DIR/versions/deps/$FILENAME.spec

$BASEPATH_DIR/scripts/buildsrc $FILENAME
