#!/bin/bash

source $(dirname "$0")/common-functions

VERSION=$(get_version)

if [ ! -d "$BASEPATH_DIR/versions/deps" ]; then
        echo "SPECs for version $VERSION not generated"
        exit 1
fi


for RPMPACKAGE in $@; do

if [ ! -f "$BASEPATH_DIR/rpmbuilds/$VERSION/SRPMS/$RPMPACKAGE" ];then
	SRPMALT=$(echo $SRPM |sed 's/python/python3/g')
	if [ ! -f "$BASEPATH_DIR/rpmbuilds/$VERSION/SRPMS/$SRPMALT" ];then
		echo "Source file: $BASEPATH_DIR/rpmbuilds/$VERSION/SRPMS/$RPMPACKAGE, doesn't exist.."
		exit 2
	else
		SRPM=$SRPMALT
	fi
fi

done

mkdir -p "$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS/"

cd "$BASEPATH_DIR/rpmbuilds/$VERSION/RPMS/"

for RPMPACKAGE in $@; do

mock -r epel-9-x86_64 --clean &> /dev/null 

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

build_rpm $RPMPACKAGE

done
