#!/bin/bash

VERSION=$(cat /opt/awx-rpm-v2/working-version)
PACKAGE=$2

if [ ! -z $1 ];then
	VERSION=$1
	/opt/awx-rpm-v2/scripts/changeversion $VERSION
fi

if [ ! -d "/opt/awx-rpm-v2/versions/deps/original" ]; then
	echo "SPECs for version $VERSION not generated"
	exit 1
fi

echo "Fetching sources for version $VERSION"

cd "/opt/awx-rpm-v2/versions/deps/"

if [[ $PACKAGE == "" ]];then
	for i in `ls *.spec`;do 
		spectool -gR --define "_topdir /opt/awx-rpm-v2/rpmbuilds/$VERSION/" $i 
	done
else
	if [ -f $PACKAGE.spec ];then
		spectool -gR --define "_topdir /opt/awx-rpm-v2/rpmbuilds/$VERSION/" $PACKAGE.spec
	else
		spectool -gR --define "_topdir /opt/awx-rpm-v2/rpmbuilds/$VERSION/" python-$PACKAGE.spec
	fi
fi
