#!/bin/bash

GNUPGHOME=/opt/awx-rpm-v2/gpg/

VERSION=$(cat /opt/awx-rpm-v2/working-version)

if [[ $VERSION == "" ]];then
	echo "Version is not defined"
	exit 1
fi

rm -rf /var/www/html/AWX-RPM/$VERSION/

cp -a /opt/awx-rpm-v2/rpmbuilds/$VERSION/RPMS /var/www/html/AWX-RPM/$VERSION

for i in `ls /var/www/html/AWX-RPM/$VERSION/*.rpm`;do

	rpm --addsign $i

done

createrepo_c /var/www/html/AWX-RPM/$VERSION/

restorecon -r /var/www/html/AWX-RPM/$VERSION
